[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "bulcd-early-detection"
version = "0.1.0"
description = "Early detection and monitoring of forest disturbance using BULC-D."
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]
